Font swapping
dataclay/event-scripts pull request #4
Opened 2019-11-18 22:47 UTC by blakmarkit

added font swapping script based on script by Shane Murphy @ prender.co and updated Extendscript API documentation URL in all scripts

2019-11-18 22:58 UTC, ariestav requested changes
No need to include the .vscode/launch.json or the ExtendScript/launch.json files in the repo.  Can you untrack them and add to .gitignore so git does not pick them up any longer?

2019-11-19 02:09 UTC, blakmarkit commented
branch should be updated.

2019-11-19 02:16 UTC, ariestav commented on .gitignore
> +/Extendscript/launch.json
This needs "Extendscript" to be "ExtendScript" I think

2019-11-19 02:23 UTC, blakmarkit commented on .gitignore
> +/Extendscript/launch.json
you are correct. updated.

2019-11-19 02:25 UTC, merged